import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import VideoList from "@/components/VideoList";

const inter = Inter({ subsets: ["latin"] });

type Video = {
  category: string;
  video: string;
  image: string;
  createdAt: number;
};

type VideoList = {
  data: Video[];
};

export default function Home({ data }: VideoList) {
  const sortedData = data.sort((a, b) => b.createdAt - a.createdAt);
  console.log(sortedData);

  const filteredVideos = sortedData.slice(0, 5);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="app">
        <VideoList title="Recents" videos={filteredVideos} />
      </main>
    </>
  );
}

export async function getServerSideProps() {
  const res = await fetch(
    "https://assets.dev.verse-core.vrse.gg/frontend-interview/data.json"
  );
  const data = await res.json();

  return {
    props: {
      data,
    },
  };
}
